# Generated by Django 4.0.4 on 2022-06-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_duvida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duvida',
            name='descricao',
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('duvida_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.duvida')),
            ],
        ),
    ]
